version: '3'

services:
  app:
    build: .
    image: portifolio
    expose:
      - 8000
    env_file: .env
    depends_on:
      - postgres
    command: wait-for-it postgres:5432 -- gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    # healthcheck:
    #   test: pg_isready -U devpro-rest
    #   interval: 2s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 3s

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres: