version: '3'

services:
  app:
    build: .
    image: portifolio
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres
    command: wait-for-it postgres:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:13.4-buster
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    # healthcheck:
    #   test: pg_isready -U devpro-rest
    #   interval: 2s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 3s

volumes:
  postgres: